language: java

jdk:
  - openjdk11
  
addons:
  sonarcloud:
    organization: "wgancarz-github"
    token:
      secure: "GeMk6sSmi9G2ZbaI27OOUB8qzVsrsXY06dSrGZfHVzHBzzY16NxJ0okDOcBPIRFjMf+dpZpo7v2UPvUNGZp7c1r9FEQ/5BxPl6E04e0QLZeHFncjiA6vGOdplsC+fl3j+0BjALf9YOrXEH9BbD4trBDZpzXZsDZMZf6YbfEX70QZWGAXpp7swwaHxb5tzrS+8ew6j+Xtj3SSqcDvKg9Ct2jwhBw8a3zfa5J86ZwGdPN88XpJK4vf4tIqZtsjhI7N6MJ/j8C5n055I0j1IrCh4Gbq8mOjX1fMmMU5fdR/j99l8P/0EEtkDAJICvXGkeo/BfCoOIFZBCbgKXILiBM6p6ET9Bw7pJ+L5gZXyI1y8EPXY2udX4n5/SpnXuaQBPta6d0MXnaIU3zyR1KUrY+F4SNMenfTiaYvvgg/cDTYcAvY/HECxP3g1d3/m2tVPG4Hck6CKnevZaxLCgyfwdLjubiKCqMmsFQdHBzkx/P+PtQWghOtrmXK4ySMj4Ni1H9tOrXUp5BD2xV489PrnzIAt8jznunmRH0Ksxj09hGFMgltrXZ4Lga13MdTBPIkNIG8k2E5zZpClw+EvavAucBxATwsapsxcgFMt5QhEZcKyT4YY1CyJ8GfOFE2f8dO+XZS+wIfy2BbX8pf9nXBxkalpa9e96L7Lh4t8zFHdGBVOdI="

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'