name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '16'
    - name: Compile
      run: mvn -B test-compile --file pom.xml
    - name: Test
      run: mvn -B org.jacoco:jacoco-maven-plugin:prepare-agent test --file pom.xml
    - name: Build Maven package
      run: mvn -B package --file pom.xml
    - name: SonarCloud scan
      run: mvn -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
